### ISSUE TITLE
Installable for VS2019. But not visible after install

### ISSUE THREAD

**Issue by Danthar** [unchase/Unchase.Odata.Connectedservice#1]
You can install this plugin for VS2019. But after installing the connected service is not visible in the 'Connected Services' UI.

**Comment by unchase** [comment]
Relevant bug report https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html

Connected Services will be restored in the first update to Visual Studio 2019 (version 16.1).

**Comment by erotavlas** [comment]
Is that why the screen for Connected Services looks nothing like the one in your animated gif? (i.e. nowhere to specify setting for the OData endpoint)

**Comment by unchase** [comment]
The OData endpoint sets in the first page of the wizard in combobox labled "OData metadata URI (path):". You can see this in the first [animated gif](https://github.com/unchase/Unchase.Odata.Connectedservice/blob/master/img/Unchase-OData-Connected-Service.gif).

**Comment by erotavlas** [comment]
Actually I dont see anything like your screen at all.  I created a asp.net web api 2 project with Odata enpoint, which works fine and I can see the metadata.  Then I created a Console App from which I wanted to connect to the endpoint.  After I installed your extension in VS 2019 I see something called Connected Services in the projects.  When I right click I see these options

<img width="551" alt="Screen Shot 2019-05-02 at 8 40 15 AM" src="https://user-images.githubusercontent.com/10454265/57075928-4c368580-6cb6-11e9-93db-b28476f1a118.png">

When I double click it (or select add connected service from the menu) I get this

<img width="588" alt="Screen Shot 2019-05-02 at 8 40 49 AM" src="https://user-images.githubusercontent.com/10454265/57075954-5bb5ce80-6cb6-11e9-8f9b-5efcf8c29508.png">

When I click the link below ' Fine new service' I get this

<img width="791" alt="Screen Shot 2019-05-02 at 8 41 08 AM" src="https://user-images.githubusercontent.com/10454265/57075973-6a9c8100-6cb6-11e9-8205-0628223fb113.png">

**Comment by unchase** [comment]
I apologize, did not immediately understand your question.
Yes, it is for this reason that the connected service is not displayed.

At the moment (until release of Visual Studio 2019 v16.1) you can generate client code from Visual Studio 2017, and then copy the files into your project.

**Comment by zeng16107** [comment]
i met the some issues when using the visual studio 2019 v16.0.3.

**Comment by unchase** [comment]
Need to wait for the Visual Studio 2019 v16.1 Release. See relevant [bug report](https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html).

**Comment by unchase** [comment]
Starting from Visual Studio Community 2019 v16.1.3 extensions based on Microsoft Connected Services now work fine.
