### ISSUE TITLE
CS8103 Combined length of user strings used by the program exceeds allowed limit because of embedded Edmx

### ISSUE THREAD

**Issue by JohnLeyva** [unchase/Unchase.Odata.Connectedservice#11]
Edmx included in Reference.cs could be very big, which generates the following error while compiing

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8103	Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.	PROJECTXXXX	PATHYYYY	1	Active

```
        private abstract class GeneratedEdmModel {
          private const string Edmx = @"....";
  }
```

An option is to include the metadata file in the project as content

**Comment by unchase** [comment]
Hi, @JohnLeyva 
Can you send me (spiritkola@hotmail.com) a file with metadata so that I reproduce the error?

**Comment by JohnLeyva** [comment]
Hi  Nickolay

I included the metadata file,

The generation works in VS2019, but does not compile because of the indicated issue.

To open generated files in some occasions is better to use vs code.

Regards

John

________________________________
