### ISSUE TITLE
DTD Prohibited When Creating (or Updating) a Service

### ISSUE THREAD

**Issue by alaskanrogue** [unchase/Unchase.Odata.Connectedservice#13]
### Describe the bug

Have a WCF Entity Framework OData service which was successfully connected to by the client using the wizard. The initial service was implemented with no security which is being re-programmed to support basic security using message interception. In client, when attempting to initially update the connection encountered "DTD is prohibited in the XML Document." Subsequently attempting to create a new connect to encounter the same error.

### Assemblies affected

Unknown

### Steps to reproduce

1. Complete required fields and options
2. Select Finish

### Expected result

Update of model

### Actual result

Error message encountered

### Screenshots

![2019-09-29 212110](https://user-images.githubusercontent.com/14001196/65843416-8f496300-e2ff-11e9-9700-437bbecfafa9.png)

### Additional detail

Assuming from error message that the XMLReader in the wizard needs to have an option enabled for DTD processing to read the response from the service.

**Comment by axellejamous** [comment]
Experiencing this exact issue with Basic Authentication.
Did you solve this as it was closed?

**Comment by alaskanrogue** [comment]
@axellejamous To be honest, I don't remember. I would assume that subsequent attempts to use the wizard succeeded as I didn't contest the closure.
