### ISSUE TITLE
Error adding connected service

### ISSUE THREAD

**Issue by goedo** [unchase/Unchase.Odata.Connectedservice#16]
Hello!
I think this is a bug...
I'm trying to access the odata feed of a standard business application (myFactory)...

The referred fields OP-Nummer ist declared int the metadata as:
<Property Name="OP-Nummer" Type="Edm.String" />
It's not wrong I think...?

Can you get back to me?
Thanks a lot!
My metadata:
https://cloud.myfactory-ondemand.ch/saas2/odata_5CYAGwHM/$metadata

Roger
![image](https://user-images.githubusercontent.com/20025525/68551227-00099200-040b-11ea-9928-e9a8ee115b5e.png)

**Comment by unchase** [comment]
Hello.
It is not a bug. You cannot use the "-" character in variable naming. Just rename this and it will works.

**Comment by goedo** [comment]
OK I see (and thank Nickolaj for your fast answer!) that there are hyphens in property names and this is illegal.
<xs:simpleType name="TSimpleIdentifier">
    <xs:restriction base="xs:string">
      <xs:maxLength value="480" />
      
      <xs:pattern value="[\p{L}\p{Nl}][\p{L}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Pc}\p{Cf}]{0,}" />
    </xs:restriction>
  </xs:simpleType>

My problem, however, is that this i a 3rd-party standard app which well works with powerpivot and others, so it will be hard to convince them to change the property names :-(
Thanks in the mean time; I will save the metadata locally, change the hyphen, and then see what happens when I connect to th odata feed...
Bye
Roger

**Comment by goedo** [comment]
Help!
Even correcting the hyphen, it will not read my XML; for a test, I reduced it to the "Lieferanten" part, and then the tool gives me:

[11.11.2019 09:46:18.922] Unchase OData Connected Service wird dem Projekt hinzugefügt.
[11.11.2019 09:46:18.922] Adding service instance...
[11.11.2019 09:46:18.925] Adding Nuget Packages for OData V3...
[11.11.2019 09:46:18.933] Nuget Package "System.ValueTuple" for OData V3 already installed.
[11.11.2019 09:46:18.937] Nuget Package "System.ComponentModel.Annotations" for OData V3 already installed.
[11.11.2019 09:46:18.942] Nuget Package "Microsoft.Data.Services.Client" for OData V3 already installed.
[11.11.2019 09:46:18.947] Nuget Package "Microsoft.Data.OData" for OData V3 already installed.
[11.11.2019 09:46:18.951] Nuget Package "Microsoft.Data.Edm" for OData V3 already installed.
[11.11.2019 09:46:18.956] Nuget Package "System.Spatial" for OData V3 already installed.
[11.11.2019 09:46:18.958] Nuget Packages for OData V3 were installed.
[11.11.2019 09:46:18.961] Generating Client Proxy for OData V3...
[11.11.2019 09:46:19.023] Fehler:Fehler beim Hinzufügen von Unchase OData Connected Service zum Projekt: Das angegebene Schema ist ungültig. Fehler: 
(0,0) : Fehler 0075: Schlüsselteil: 'PK_LieferantID' für Typ Lieferanten ist ungültig. Für sämtliche Teile des Schlüssels dürfen keine NULL-Werte zulässig sein.

Someone getting the same problem?
Thanks a lot!

**Comment by unchase** [comment]
Looks like the edm-schema specified is not valid for **OData** validation into the generation library that used by the Connected Service. I try to comment some parts of the schema, but have some errors:

1. "_Name Zentralregulierer cannot be used in type Myfactory.Models.Zentralregulierer. Member names cannot be the same as their enclosing type._" **line: 1716**

1. There are a few "_EntityType has no key defined. Define the key for this EntityType._": 
* 'Myfactory.Models.Projektbudgets'
* 'Myfactory.Models.ArtikelZusatzartikel'
* 'Myfactory.Models.Verkaufpreise'
* 'Myfactory.Models.ArtikelVariantenDimensionswerte'
* 'Myfactory.Models.EinkaufUmsatzdetails'
* 'Myfactory.Models.VerkaufAuftragschancen'
* 'Myfactory.Models.VerkaufAuftragseingang'
* 'Myfactory.Models.VerkaufUmsatzdetails'
* 'Myfactory.Models.VK_OffeneBelege'
* 'Myfactory.Models.VerkaufBudgetArtikel'
* 'Myfactory.Models.VerkaufBudgetArtikelgruppen'
* 'Myfactory.Models.VerkaufBudgetBetriebsstaetten'
* 'Myfactory.Models.VerkaufBudgetKunden'
* 'Myfactory.Models.VerkaufBudgetKundengruppen'
* 'Myfactory.Models.VerkaufBudgetVertreter' 
* 'Myfactory.Models.VerkaufBudgetVertretergruppen'
* 'Myfactory.Models.SachkontoBudget'
* 'Myfactory.Models.BuchungenKosten'
* 'Myfactory.Models.ZeiteintraegeSpesen'
* 'Myfactory.Models.Dispoeintraege'
* 'Myfactory.Models.Lagerbestaende'
* 'Myfactory.Models.Lagerbuchungen'
* 'Myfactory.Models.DimDatum'
* 'Myfactory.Models.DimPeriode'

**Comment by goedo** [comment]
Hi Nikolaj!
I had a break, now  I'm back again with my problem :-)
Basically your generator now works without problems. The issues i've got are:
- On runtime, I have to substitute the local XML file with the real URL like this:
static void Main(string[] args)
        {
            MyfactoryService s = new Myfactory.Models.MyfactoryService();
            //MyfactoryService s = new Myfactory.Models.MyfactoryService(new Uri("https://cloud.myfactory-ondemand.ch/saas2/odata_5CYAGwHM"));
            DataServiceQuery selectedLieferanten = s.Lieferanten
                .AddQueryOption("$filter", "PK_LieferantID = 2");
        }
Right?
- despite I gave the credentials, I do not see any use of the credentials which I find in ConnectedService.json - is this right?
- and of course: I've got no clue how to program a very simple get-it-all-query. Are there some examples for this?
Thank you in advance - and spassibo agromnie!

**Comment by goedo** [comment]
Hi!
Now my program works, but not as expected by design. I had to to some workarounds:
## This does not work:
*  MyfactoryService s = new MyfactoryService();
*  var credentials = new NetworkCredential("xxx", "yyy");
*  DataServiceContext ds = new   
 * ds.Credentials = credentials;
## This works: changing referenceExtensions.cs 
*  adding: using System.Net;
* changing public void InitProperties(), adding
  * this.Credentials = new NetworkCredential("xxx", "yyy");  
* as well as changing the constructor, making it point to the service an not to the local file (which I needed, because some variables had "-" in their name, as well as keys missed the nullable="false" parameter...
  * public MyfactoryService() : this(new Uri("https://cloud.myfactory-ondemand.ch/saas2/odata_5CYAGwHM"))

## Question:
What do you do with the user and pwd asked for at generation, which you write in the json file? It's never used :-(

Last but not least: filtering does not work, not even with Postman. Is this due to the service implementation at myFactory's home?

С уважением!
Roger

**Comment by goedo** [comment]
> Looks like the edm-schema specified is not valid for OData validation into 

...For my tests I use only Lieferanten. In prod, Kunden and Einkaufsbelege do work as well...

**Comment by unchase** [comment]
Hi, @goedo !
1) Network credentials wich saved to json file used only for getting the metadata for generating client code.
If you want to use them, should to add them with standart way in the code.

2) I can’t answer this question with accuracy, since this is an internal implementation of filtering into libraries, which is used by generated client code.
