### ISSUE TITLE
Possible bug: Content-Type: application/json; charset=utf-8 is not supported.

### ISSUE THREAD

**Issue by carmalou** [unchase/Unchase.Odata.Connectedservice#17]
Content-Type: application/json; charset=utf-8 is not supported. When attempting to call out to my node server I receive the following error:

![image](https://user-images.githubusercontent.com/7669975/69060716-7004b300-09dd-11ea-822f-f5f7940e8b40.png)

**Comment by unchase** [comment]
Please send the metadata file to email spiritkola@hotmail.com

**Comment by unchase** [comment]
Hi, @carmalou 
I cant help you with your issue without the metadata file.
