### ISSUE TITLE
Create entities as separate classes for reverse scaffolding

### ISSUE THREAD

**Issue by dwarak123** [unchase/Unchase.Odata.Connectedservice#18]
Hello, 

I am a test automation analyst trying to build a framework for the Australian Department of Human Services to test OData which is exposing SAP entities and resources. I found this very useful to auto generate classes from metadata. As I am only testing this not consuming in the traditional sense I need to simulate the user input through simulation and I am having to maintain the database tables for the entities to store the input data. I have seen example where a class in the visual studio C# can be scaffold to create a table in the connected SQL server. Is this possible at all.

**Comment by unchase** [comment]
Hello, @dwarak123 
This feature is currently not supported by the Connected Service.
