### ISSUE TITLE
How to fix wrong naming?

### ISSUE THREAD

**Issue by DavidMChristiansen** [unchase/Unchase.Odata.Connectedservice#19]
I got a property with a name starting with underscore, i ahve to remove it from the metafile before Unchase will accept the metafile, is it possible to get it to accept the name with starting underscore?
`<Property Name="_x003C_Document_Exchange_Status_x003E_" Type="Edm.Boolean"/>`

**Comment by unchase** [comment]
You can fix all incorrect variable names (methods), generate code, and then rename them in the generated code.
