### ISSUE TITLE
Adding Unchase OData Connected Service to the project failed

### ISSUE THREAD

**Issue by SoftVahid** [unchase/Unchase.Odata.Connectedservice#20]
i got this error when i was tried to connect CRM Dynamics 365 Metadata link:

**Failed to access the metadata document. The OData service requires authentication for accessing it. Please download the metadata, store it into a local file, and set the value of “MetadataDocumentUri” in the .odata.config file to the file path. After that, run custom tool again to generate the OData Client code**

**Comment by unchase** [comment]
Hi, @SoftVahid.
Have you used network credentials for connecting to the endpoint (metadata file)?

![1_wO_Zzs6pEXTDBxlaZ8ANyA](https://user-images.githubusercontent.com/29679226/70975146-66449d00-20ba-11ea-88d8-dabc06b1a3a5.png)

P.S. If your network used Proxy, you should specify options in the `Web Proxy` section.

**Comment by unchase** [comment]
Try to save the metadata file and generate code from it.
