### ISSUE TITLE
Why create URI class ?

### ISSUE THREAD

**Issue by premiaware** [unchase/Unchase.Odata.Connectedservice#22]
I have try to migrate my App that use OData v4 Client Code Generator to Unchase.
My problem is that Unchase generate 

namespace System
{
    /// <summary>
    /// There are no comments for Uri in the schema.
    /// </summary>
    public partial class Uri
..........

and

namespace System.Net.Mime
{
    /// <summary>
    /// There are no comments for ContentType in the schema.
    /// </summary>
    public partial class ContentType
    {

my app to connect odata service use :
 _containerPrimario = new Default.Container (new Uri(_serviceUri, UriKind.RelativeOrAbsolute));

but uri is generated from unchase and not work.

how can i exclude the uri from generation?

**Comment by unchase** [comment]
Classes are generated according to the metadata schema. If there is a class **"Uri"** in the metadata, then it will be generated.
When initializing the container, you must specify the correct namespace for Uri (*System.Uri*).
In addition, you can exclude a class after generation by deleting it if it is not needed.

**Comment by premiaware** [comment]
Ok i have fix the problem, 
but now i have this error: (you can help to me?)

Error	CS0234	The type or namespace name 'Text' does not exist in the namespace 'FastHomeMobile.LogicUI.DataSource.System' (are you missing an assembly reference?)	FastHomeMobile.LogicUI	C:\Work\UniversalApps\FastHomeMobile\FastHomeMobile.LogicUI\Service References\FHServices\Reference.cs	57973	Active

the row:
 global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
is must manual replace it with:
 global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();

the complete code is:

 private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }

**Comment by unchase** [comment]
Can you send to spiritkola@hotmail.com the metadata file?
