### ISSUE TITLE
Remember setting "Add extensions code template for OData proxy-class" on update connected service

### ISSUE THREAD

**Issue by dpekmd** [unchase/Unchase.Odata.Connectedservice#23]
### Describe the bug
When adding a new Connected Service for OData, then it is possible to set different parameters in the Wizard UI.
One important setting for us is to be able to un-check the "Add extensions code template for OData proxy-class" as we create our own code for that.

When updating the existing Connected Service, then it seems that the advanced setting "Add extensions code template for OData proxy-class" is not remembered and since the advanced settings are collapsed, it is easy for a developer to miss that and accidently generate the ReferenceExtensions.cs file.

### Expected result

Excepted that all settings initially set, are be remembered when updating the connected services and just clicking "Finish".

### Actual result

The setting "Add extensions code template for OData proxy-class" seems to be forgotten and this results in an unwanted ReferenceExtensions.cs file being generated.

**Comment by unchase** [comment]
Fix it in [v1.3.8](https://github.com/unchase/Unchase.Odata.Connectedservice/releases/tag/v1.3.8).
