### ISSUE TITLE
Question: AutoUpdate Collection

### ISSUE THREAD

**Issue by Gforse12** [unchase/Unchase.Odata.Connectedservice#25]
When a Entity is created/updated on the server the server than returns the entity in the repsone body. Is there a way/boolean that takes this data and automatically update the collection? For example when creating a Entity the ID is empty because this is generated on the server. If we POST a new Entity to the server the server will return the newly created Entity WITH the ID value.

**Comment by unchase** [comment]
This issue relates to the work of the client library. Create the same issue in the [repository](https://github.com/OData/odata.net/issues).

**Comment by Gforse12** [comment]
Thanks, i posted it on that repository: [](https://github.com/OData/odata.net/issues/1622)
