### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Gforse12** [unchase/Unchase.Odata.Connectedservice#26]
When i have a object that contains a collection than the collection is serialized as [].

For example:
`````
Public WebCon As New Container(New Uri(serverBaseUrl))
Private dsqProductAttributes As DataServiceQuery(Of ProductAttribute) = CType(WebCon.ProductAttributes.Take(120), DataServiceQuery(Of ProductAttribute))

Dim x As New ProductAttribute With {.Name = "API_Test_" & Now.ToString}
x.ProductAttributeOptionsSets.Add(New ProductAttributeOptionsSet With {.Name = "Default"})
WebCon.AddToProductAttributes(x343)
WebCon.SaveChanges()
`````

Then when i captured the POST command with wireshark only the `Name` is serialized but the `ProductAttributeOptionsSets` is missing. Also the other way arround when i GET `ProductAttributes` then the `ProductAttributeOptionsSets` is `[]`

I tested with other collection and all result in the same. It seems that is an object containt a collection this isn't parsed/requested?

**Comment by unchase** [comment]
Hi, @Gforse12 

Can you send the metadata file to spiritkola@hotmail.com?

**Comment by Gforse12** [comment]
Check your mail :-)
