### ISSUE TITLE
BUG: Can't update generated .vb file after the Connected Service updating

### ISSUE THREAD

**Issue by Gforse12** [unchase/Unchase.Odata.Connectedservice#27]
I recently updated the `1.3.7.0` to vX and i have a .vb generated code class. When i run `Update Unchase OData Connected Services` the option `Generating Language` is disabled. So it seems that on update only .cs files are updated/supported?

**Comment by unchase** [comment]
Hi, @Gforse12 

Thanks for the issue. I fixed it in the [last release](https://github.com/unchase/Unchase.Odata.Connectedservice/releases/tag/v1.3.9). Please, check it now.

**Comment by Gforse12** [comment]
Tried the update but stil only a .cs can be generated, check screensnip:
![Unchase OData Update only CS](https://user-images.githubusercontent.com/36954910/72329477-1a831480-36b5-11ea-8424-25d769a1fade.png)

**Comment by unchase** [comment]
First you should change the `LanguageOption` value to `1` in ConnectedService.json file. Or regenerate generated file.

**Comment by Gforse12** [comment]
Check, that works! :-)
