### ISSUE TITLE
Having trouble using Connected Service in .Net Standard

### ISSUE THREAD

**Issue by ChrisSchaller** [unchase/Unchase.Odata.Connectedservice#28]
After running through the wizard in a brand new .NET standard project there are 2 errors:
(both the same thin really)

- Loading the include file 'Reference1.ttinclude' returned a null or empty string. The transformation will not be run.
- Failed to resolve include text for file:C:\Users\chris\source\repos\standard1\standard1\Connected Services\SkyMove\Reference1.ttinclude	standard1	

When I look in the file system, the` Reference1.ttinclude` file is there but the Reference1.cs has the "ErrorGeneratingOutput" content.

If I then try to execute the Reference1.tt file manually the following errors are now observed:

- Compiling transformation: Method must have a return type … (line: \Reference1.tt	7464)
- Compiling transformation: Invalid token 'this' in class, struct, or interface member declaration	standard1	C:\Users\chris\source\repos\standard1\standard1\Connected Services\SkyMove\Reference1.tt	7464	
 	

----
Microsoft Visual Studio Professional 2019
Version 16.4.3

**Comment by ChrisSchaller** [comment]
I haven't done it yet, but I want to edit the include scripts because some methods are being generated with duplicate parameter names. 'source'

**Comment by unchase** [comment]
Try to uncheck `Add code templates (Whether to include the T4 files into this project)` option on `Advanced Settings` wizard page.

**Comment by ChrisSchaller** [comment]
Yeah that works, but I want to modify the `.ttinclude` because there are some parameter name conflicts with the model I am targeting.

**Comment by ChrisSchaller** [comment]
I'll consider making a PR, I'd like to introduce the convention of prefixing extension type parameters with an underscore. In my projects I use `_self` as the type parameter, but simply using the `_` is normally enough to reduce potential conflicts. So changing to `_source` should be enough as it would be more unusual for an API to expose arguments with an underscore. If you like the idea, I'm happy to put in the hack work to get it done.

**Comment by unchase** [comment]
Create a pull request and I will review it)
You may find errors that I have not noticed.

**Comment by ChrisSchaller** [comment]
I’ll think about a PR but it might take longer to polish off as I’ve made substantial changes now as the need of my team have dictated the following requirements:


  *   Ability to specify the base class to inherit from (as an advanced setting)
  *   Change the INotifyPropertyChanged implementation to support asynchronous notifications when bound to the UI
  *   If the base class implements INotifyPropertyChanged, to call OnPropertyChanged or RaisePropertyChanged from the base class
  *   Change the name of the extension type parameter in extension methods to underscore (_)
  *   Import doc comments from custom XML files (expecting the XML files produced by the API dlls)
  *   Other proprietary conventions.

All of this I normally would have implemented as customisations to the .ttinclude  file, which is why I was expecting to use that feature.
Its a great implementation of the old OData client scripts that we were using, so well done!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by unchase** [comment]
You can work on PR at a convenient time. In any case, your improvements will be very useful to the community and will help the development of the project as a whole.

**Comment by unchase** [comment]
I merged your [PR](https://github.com/unchase/Unchase.Odata.Connectedservice/pull/31). Thanks!
