### ISSUE TITLE
Creating Unchase OData V1-V4 Connected Service

### ISSUE THREAD

**Issue by gem81** [unchase/Unchase.Odata.Connectedservice#3]
somewhere between
[11.04.2019 17:43:49.073] Generating Client Proxy extensions class for OData V3...
[11.04.2019 17:43:50.147] Error: Remote host ...... : (401) Unauthorized..
[11.04.2019 17:43:51.786] Client Proxy extensions class for OData V3 was generated.
 
This happens only with checked 
Generate OData methods from FunctionImports.

**Comment by gem81** [comment]
as a result, functions are not created.

**Comment by unchase** [comment]
Before code generation, did you check options "Use network credentials for connecting to the endpoint :" and/or "Use web-proxy for connecting to the endpoint :" along with "Use web-proxy credentials for connecting to the endpoint :"?
What generation method did you use: "Inner" or "SimpleOData"?

What endpoint did you use?

**Comment by gem81** [comment]
> Before code generation, did you check options "Use network credentials for connecting to the endpoint :" and/or "Use web-proxy for connecting to the endpoint :" along with "Use web-proxy credentials for connecting to the endpoint :"?

Use network credentials for connecting to the endpoint: checked
Proxy not checked


> What generation method did you use: "Inner" or "SimpleOData"?
Both 

> What endpoint did you use?

"http://192.168.1.110/ut_kaskad/odata/standard.odata/"


If i try to import whith functions, its generate the same proxy class, but i see error exception 
/Unchase.OData.ConnectedService/CodeGeneration/V3CodeGenDescriptor.cs
           if (this.ServiceConfiguration.IncludeExtensionsT4File && this.ServiceConfiguration.GenerateFunctionImports)
            { 
                try
                {
                    if (EdmxReader.TryParse(XmlReader.Create(ServiceConfiguration.Endpoint), out var model, out var parseErrors))
                        functionMethods = FunctionImportsHelper.GetFunctionImportsCode(model, proxyClassName, ServiceConfiguration.Endpoint.Replace("$metadata", string.Empty), this.ServiceConfiguration.FunctionImportsGenerator);
                    else
                    {
                        foreach (var error in parseErrors)
                            await this.Context.Logger.WriteMessageAsync(LoggerMessageCategory.Warning, error.ErrorMessage);
                    }
                }
                catch (Exception ex)
                {
                    **await this.Context.Logger.WriteMessageAsync(LoggerMessageCategory.Error, $"Error: {ex.Message}.");**
                }
            }

**Comment by gem81** [comment]
It seems that at the time of generating functions, the context loses authorization, trying to make an additional request to the server.

**Comment by unchase** [comment]
Fixed in last commit (v 0.3.14). Please, check the issue.
