### ISSUE TITLE
C4C OData invalid Namespace attribute

### ISSUE THREAD

**Issue by feldschlosser** [unchase/Unchase.Odata.Connectedservice#33]
Hi,

I want to extract data from C4C via OData. I enter the metadata url, but the connected service cannot be added. It says "The 'Namespace' attribute is invalid". 
![image](https://user-images.githubusercontent.com/31888020/73439581-20812280-4350-11ea-8d95-b4da8afb353c.png)

Screenshot of metadata XML:
![image](https://user-images.githubusercontent.com/31888020/73439619-30006b80-4350-11ea-9e3a-9c48fc8387f3.png)

Thank you for your help.

**Comment by unchase** [comment]
Hi, @feldschlosser 
Can you send the metadata file to spiritkola@hotmail.com?
