### ISSUE TITLE
Cannot connect to ODATA v4 from MS Business Central

### ISSUE THREAD

**Issue by ajithnairms** [unchase/Unchase.Odata.Connectedservice#35]
I am unable to add the Reference for ODATA service published from MS Business Central.

_Following is the message after pressing finish._

Adding service instance...
Adding Nuget Packages for OData V4...
Nuget Package "Microsoft.OData.Client" for OData V4 already installed.
Nuget Package "Microsoft.OData.Core" for OData V4 already installed.
Nuget Package "Microsoft.OData.Edm" for OData V4 already installed.
Nuget Package "Microsoft.Spatial" for OData V4 already installed.
Nuget Packages for OData V4 were installed.
Generating Client Proxy for OData V4...
Error:Adding Unchase OData Connected Service to the project failed: Failed to access the metadata document. The OData service requires authentication for accessing it. Please download the metadata, store it into a local file, and set the value of “MetadataDocumentUri” in the .odata.config file to the file path. After that, run custom tool again to generate the OData Client code.

**Comment by unchase** [comment]
Hi, @ajithnairms 
Did you use `Network Credentials` or `Web Proxy` credentials?

**Comment by ajithnairms** [comment]
Hello,

I made use of Network Credentials.

Regards
Ajith Nair

**Comment by ajithnairms** [comment]
Hello,

Let me know the options to be selected from Advanced Settings (from screen 2). The highlighted options were not selected earlier. Even after selecting them, the only positive thing is that the connection was established but still the referencing is not possible as the entire code seems to be commented due to some reason.

[cid:image001.png@01D5E0C8.42647AE0]

Screenshot of .ttinclude file.

[cid:image002.png@01D5E0C8.42647AE0]

Screenshot of .cs file

[cid:image003.png@01D5E0C8.42647AE0]

Regards
Ajith Nair





Confidentiality Notice: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail, delete and then destroy all copies of the original message.

**Comment by ajithnairms** [comment]
Hi,

Thanks for your support. It was able to connect with Odata V3 and it is working fine. V3 advanced settings below.

If you can check and let me know what is the issue with v4 it would be good.

[cid:image001.png@01D5E0FD.91C6F2E0]

Regards
Ajith Nair



Confidentiality Notice: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail, delete and then destroy all copies of the original message.

**Comment by unchase** [comment]
Hi.

I can't see all the screenshots. You should send them from email directly (not from github).

**Comment by ajithnairms** [comment]
I had replied directly from mail along with screenshots. 

I cant paste it here.

**Comment by ajithnairms** [comment]
By unchecking below option , it does not work at all and gives the same error that I shared initally.
`Add code templates (Whether to include the T4 files into this project).`

**Comment by ChrisSchaller** [comment]
If connecting with the v3 logic works, then perhaps that is all you need to do, according to the docs, 

> The Business Central implementation of EDM follows the .NET 4.0 WCF Data Service Framework implementation.

Which approximates and older preview of the OData v4 specification. We really need to see those screenshots to help more, perhaps you can use another forum like www.stackoverflow.com to post your issues there and link back to this issue, with that or upload your images to a public host and paste in the links.

**Comment by ziacik** [comment]
I have the same problem. The thing is, with network credentials, the extension adds `Authorization` header (after getting 401) the first time - when I click "Next" button - but doesn't add it the second time - when I click "Finish" button to actually generate stuff.

**Comment by unchase** [comment]
> I have the same problem. The thing is, with network credentials, the extension adds `Authorization` header (after getting 401) the first time - when I click "Next" button - but doesn't add it the second time - when I click "Finish" button to actually generate stuff.

Have you tried to download the metadata file, and use it locally to generating client code?

**Comment by ajithnairms** [comment]
No. I have not tried it. Since it worked with OData V3, It did not bother me much.

Regards
Ajith Nair

**Comment by ziacik** [comment]
> 
> 
> > I have the same problem. The thing is, with network credentials, the extension adds `Authorization` header (after getting 401) the first time - when I click "Next" button - but doesn't add it the second time - when I click "Finish" button to actually generate stuff.
> 
> Have you tried to download the metadata file, and use it locally to generating client code?

No. After seeing that the client does not send the `Authorization` header, I just allowed anonymous access for a while. That allowed me to continue.

**Comment by unchase** [comment]
Hi, @ziacik  

At the moment, I am focused on improving the [Connected service](https://github.com/OData/ODataConnectedService) by Microsoft and actively contribute to it, since its development has resumed. All features will be transferred to this project. In addition, it is developing faster, so all new features will be added there.

You can create your issues in [this repository](https://github.com/OData/ODataConnectedService/issues).
