### ISSUE TITLE
Cannot find OrgConext 

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [unchase/Unchase.Odata.Connectedservice#36]
Hello, 

I have migrated my projet from .NET Framework to .NET Core, WCF is not fully supported by .NET Core. that's why I orientated to Unchase.Odata.Connectedservice but when i generate oData, i don't find OrgContext in Reference.cs

Appreciate any assistance or suggestions. Thank you

**Comment by unchase** [comment]
Hi, @HASSEN-MEDDEB-ATOS 

To help you, I need the content of the metadata (xml) generated by OData.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello @unchase

can you give your mail please, i can't upload xml file in this Form

Best regards

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello again,

I have sent the file to this mail  spiritkola@hotmail.com

Cordially

**Comment by unchase** [comment]
The Connected Service generates only those classes (contexts) that are in the metadata file. If `OrgContext` is not in the metadata, then it will not be in the generated client code. Perhaps he has a different name.
