### ISSUE TITLE
Problem with navigation property in complex type

### ISSUE THREAD

**Issue by hugener** [unchase/Unchase.Odata.Connectedservice#38]
I'm trying to consume an OData service and the code generation worked just fine.
However, when I execute a query I get the following error:
**The property 'X' is of entity type and it cannot be a property of the type 'Y', which is not of entity type.  Only entity types can contain navigation properties.**

I checked the definition and there is a complex type, which has a navigation property to an entity type. As the message states this is not supported.

However, according to the following link, it should be supported in OData Core Lib V7: https://docs.microsoft.com/en-us/odata/odatalib/navigation-under-complex
I'm not sure though, if that version maps to the dlls used by the generated connected service:
Microsoft.OData.Client 7.6.3
Microsoft.OData.Core 7.6.3
Microsoft.OData.Edm 7.6.3
etc.

I don't control the service I'm consuming, so I can't change that.
Does anyone know if it's possible to get this to work?

**Comment by unchase** [comment]
You should to create the issue in [this repository](https://github.com/OData/odata.net/issues).

**Comment by unchase** [comment]
[Not implemented yet](https://github.com/OData/odata.net/issues/1678) in the client library.
