### ISSUE TITLE
BUG Member names cannot be the same as their enclosing type.

### ISSUE THREAD

**Issue by zeng16107** [unchase/Unchase.Odata.Connectedservice#4]
### Describe the bug
Thanks for this awesome connected service. and i use this connected service in vs2017 to generate the service proxy files for sap success factor's odata api. but i met the issues below:

Error:Adding Unchase OData Connected Service to the project failed: Schema specified is not valid. Errors: 
(0,0) : error 0042: Name cust_SalaryTemplate cannot be used in type SFOData.cust_SalaryTemplate. Member names cannot be the same as their enclosing type.
(0,0) : error 0042: Name cust_Dependents cannot be used in type SFOData.cust_Dependents. Member names cannot be the same as their enclosing type.
(0,0) : error 0042: Name cust_PaySlip cannot be used in type SFOData.cust_PaySlip. Member names cannot be the same as their enclosing type.
(0,0) : error 0042: Name cust_TrainingTotal cannot be used in type SFOData.cust_TrainingTotal. Member names cannot be the same as their enclosing type.
(0,0) : error 0042: Name cust_ContractSalary cannot be used in type SFOData.cust_ContractSalary. Member names cannot be the same as their enclosing type.

### Assemblies affected

*Which assemblies and versions are known to be affected?*
vs2017.

### Steps to reproduce

as normal steps.

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known.*

**Comment by unchase** [comment]
Could you please send a your json-specification so that I can solve the issue?
