### ISSUE TITLE
Operation is not supported on this platform.

### ISSUE THREAD

**Issue by amourrashid** [unchase/Unchase.Odata.Connectedservice#46]
When trying to use ODada Connected Service with Client Side Blazor all initial processes for client generation seems smooth. However the proxy generated works only with the server side blazor.
With Client Side Blazor it gives an error
System.PlatformNotSupportedException: Operation is not supported on this platform.
Any idean on how sort this out.

**Comment by unchase** [comment]
Hi, @amourrashid 

This issue is not related to the Connected service or code generation.
See https://github.com/OData/odata.net/issues/1786 and https://github.com/OData/odata.net/issues/1784
