### ISSUE TITLE
Cannot convert from 'System.Xml.XmlReader' to System.Collections.Generic.IEnumerable<System.Xml.XmlReader>'

### ISSUE THREAD

**Issue by Pantzer-byte** [unchase/Unchase.Odata.Connectedservice#47]
### Describe the bug
When generating model classes, I get two errors in my LoadModelFromString method in the Reference.cs class:

		private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
		{
			global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
			try
			{
				global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
				global::Microsoft.OData.Edm.IEdmModel edmModel;
				
				if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
				{
					global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
					foreach (var error in errors)
					{
						errorMessages.Append(error.ErrorMessage);
						errorMessages.Append("; ");
					}
					throw new global::System.InvalidOperationException(errorMessages.ToString());
				}

				return edmModel;
			}
			finally
			{
				((global::System.IDisposable)(reader)).Dispose();
			}
		}

> Argument 1: Cannot convert from 'System.Xml.XmlReader' to System.Collections.Generic.IEnumerable<System.Xml.XmlReader>'

> Argument 2: cannot convert from 'bool' to 'Microsoft.OData.Edm.IEdmModel'

I need to manually fix the code after each time the Reference class is generated via the Unchase OData Connected Service.

### Assemblies affected

Unchase OData Connected Service v1.4.1
Microsoft Visual Studio Professional 2017 15.9.28307.1093

### Steps to reproduce

1. Take [my ConnectedService.json file here](https://pastebin.com/raw/YahuCt4M)
2. Generate Reference class using[ my metadata file](https://pastebin.com/raw/tUSkbk3t)
3. The error will be present in the LoadModelFromString method of the Reference.cs class

**Comment by unchase** [comment]
Hi, @Pantzer-byte 
I tried to reproduce the issue with your data in Visual Studio 2019 v16.6.2 (and Visual Studio 2017 v15.9.23) - there are no errors:

![no errors](https://user-images.githubusercontent.com/29679226/87199989-51ed1980-c304-11ea-9727-c2ea4d160085.png)

Try to remove all generated files and generate client code again.

**Comment by Pantzer-byte** [comment]
Hey @unchase 
Thank you for your quick reply :) I will try very soon and let you know. Have a nice day!

**Comment by unchase** [comment]
Hi, @Pantzer-byte 
Have you tried it?

**Comment by cbulliraju** [comment]
Hi @unchase,

I have tried, in VS Professional 2015, Version: 14.0.25420.01 Update 3.

Same problem.

Argument 1: Cannot convert from 'System.Xml.XmlReader' to System.Collections.Generic.IEnumerable<System.Xml.XmlReader>'


Argument 2: cannot convert from 'bool' to 'Microsoft.OData.Edm.IEdmModel'

**Comment by unchase** [comment]
VS 2015 does not supports by the [Connected Service](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseODataConnectedService):

![image](https://user-images.githubusercontent.com/29679226/94114108-904c9c00-fe50-11ea-999a-84c51dbe3e1c.png)

You should use VS 2017 or VS 2019 for generating client.

**Comment by vsundupey** [comment]
Encountered with the same issue, I resolved it by updating OData Nuget packages to newer version.
