### ISSUE TITLE
How to invoke methods that use Contained entities?

### ISSUE THREAD

**Issue by SuperJMN** [unchase/Unchase.Odata.Connectedservice#48]
### Describe the bug

The generated client worked perfectly, except for one use case we have in our project. Please, take a look to the PricesController.

There is the root entity `Price` and the child entity `PriceValue`. PriceValue is set as [Contained] inside Price and we have the following methods. GetValores and PostToValores that deal with PriceValue.

![image](https://user-images.githubusercontent.com/3109851/93486158-2722d100-f904-11ea-828e-253143197147.png)

The problem is that I don't know how to invoke this method using the client. 

For example, using Postman, I can invoke the GetValores method by requesting **HTTP GET: https://localhost:44326/odata/Prices(2)/Values**

### Assemblies affected

Latest available version

### More info

I've attached the metadata of my service inside a .zip file
[$metadata.zip](https://github.com/unchase/Unchase.Odata.Connectedservice/files/5239911/metadata.zip)

**Comment by unchase** [comment]
Hi, @SuperJMN 

You can read the [microsoft docs](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v3/calling-an-odata-service-from-a-net-client#invoke-an-odata-action). Hope it helps.

**Comment by SuperJMN** [comment]
I'm sorry, Chebotov, but after reading the docs, I still don't know how to invoke the GetValores and PostToValores methods. Take into account that the PriceValue doesn't have its own controller and to query the PriceValues of a Price, it's done using those methods. Is there a solution to consume them using Unchase Odata? 

Thanks!

**Comment by unchase** [comment]
@SuperJMN 
Try to invoke this method something like this:

```csharp
// ...
using (var httpClient = new HttpClient())
{
    Uri endpointUri = new Uri("http://localhost/"); // your endpoint uri
    Default.Container container = new Default.Container(endpointUri);
    Uri actionUri = new Uri(endpointUri, "Prices(5)/Values");
    var averageRating = await container.ExecuteAsync<IActionResult>(
        actionUri, "POST", true, new BodyOperationParameter("priceValue", new PriceValue
        {
            // fill properties
        }));
}
//...
```
