### ISSUE TITLE
FEATURE: Run the extension automatically and/or via the command-line

### ISSUE THREAD

**Issue by chaniwolfson** [unchase/Unchase.Odata.Connectedservice#50]
We have an OData endpoint that is being updated on a regular basis, and I wanted to automate the generation of the proxy class, all from a backend diagnostics tools.

**Comment by absolutejam** [comment]
Exact same scenario here! Would be a really amazing addition.

**Comment by lorenzoviola** [comment]
Hello, that feature would be great

Now with VS2022 I'm forced to open VS2019 to generate class

Launching from script/command line would resolve two problems in one (time, and VS updates)

**Comment by benbward** [comment]
I'm trying to generate a proxy for Microsoft Dynamics 365 and (presumably because the OData model is so large) it crashes Visual Studio.  Perhaps a command-line version (with the ability to restrict to specific entities?) would solve this problem?

**Comment by unchase** [comment]
Hi, @benbward 
For large files with metadata, it's best to use the official [ODataConnectedService](https://github.com/OData/ODataConnectedService) from Microsoft, as it allows you to split the generated code into separate files.

**Comment by benbward** [comment]
FYI, the new OData CLI is looking pretty great for this as well, since it doesn't require the connected service and works independently of Visual Studio. With it, I'm able to generate the full object graph very quickly.

**Comment by unchase** [comment]
I will close this issue due to the fact that I cant support new features in this project. You should use more flexible [Microsoft OData Connected Service](https://github.com/OData/ODataConnectedService).
