### ISSUE TITLE
Updating to OData 4.0 breaks UI in WPF?

### ISSUE THREAD

**Issue by TripleNico** [unchase/Unchase.Odata.Connectedservice#52]
The OData backend has updated from OData v3 to v4. This is a backend managed by a thrid part. Now i updated the Unchase.OData.ConnectedService from v1.4.1.0 to v1.4.2.0. Then i rebooted the computer, opend the solution again and then Clicked on `Update Unchase ODate Connected Service...` The update all goes when and update the exists OData v3 class to v4. This goes well but when i build the solution then i get thons off errors indicating the reference to my WPF ui object can't be found anymore. Saying "SomeComponent" is not a member of "MySolution.System"

What am i overlooking here?

This is the configuration:

`
{
  "ProviderId": "Unchase.OData.ConnectedService",
  "Version": "1.4.2.0",
  "GettingStartedDocument": {
    "Uri": "http://odata.github.io/odata.net/"
  },
  "ExtendedData": {
    "EnableNamingAlias": false,
    "IgnoreUnexpectedElementsAndAttributes": false,
    "GenerateDynamicPropertiesCollection": true,
    "DynamicPropertiesCollectionName": "DynamicProperties",
    "IncludeT4File": false,
    "MakeTypesInternal": false,
    "OperationImportsGenerator": 0,
    "IncludeExtensionsT4File": false,
    "GenerateOperationImports": false,
    "ServiceName": "OData_MyClass_v4",
    "AcceptAllUntrustedCertificates": false,
    "Endpoint": "https://domain.com/odata/v1/$metadata",
    "EdmxVersion": {
      "Major": 4,
      "Minor": 0,
      "Build": 0,
      "Revision": 0,
      "MajorRevision": 0,
      "MinorRevision": 0
    },
    "GeneratedFileNamePrefix": "MyClass_v4",
    "UseNameSpacePrefix": false,
    "NamespacePrefix": null,
    "UseDataServiceCollection": false,
    "UseAsyncDataServiceCollection": false,
    "OpenGeneratedFilesOnComplete": false,
    "LanguageOption": 1,
    "FunctionImports": null,
    "OperationImports": null,
    "ExcludedOperationImportsNames": "",
    "UseNetworkCredentials": false,
    "NetworkCredentialsUserName": null,
    "NetworkCredentialsPassword": null,
    "NetworkCredentialsDomain": null,
    "WebProxyUri": null,
    "UseWebProxy": false,
    "UseWebProxyCredentials": false,
    "WebProxyNetworkCredentialsUserName": null,
    "WebProxyNetworkCredentialsPassword": null,
    "WebProxyNetworkCredentialsDomain": null
  }
}
`

In the meantime i created a new solution, added the Connected Service and exactly the same problem. The newly created solution was based on WPF, VB.NET running on .NET 4.7.2. It seems it created a namespace conflict is guess

**Comment by ChrisSchaller** [comment]
I usually work backwards in these scenarios, try to resolve the issue manually by making the necessary changes to the generated code. Once you "know" what the actual problem is, then it is easier to resolve.

Yes, you could be on the right track about the namespace but there is more to it, than that.

**Comment by TripleNico** [comment]
Thanks for you tip. I did a backtrace and in turns out the updated backend of the third party uses two namespaces: Namespace="System.Collections.Generic" and Namespace="System.Net.Http" which causes the namespace violation. Changing this to something else resolves it. So thanks for the help. This now seems to be resolved.
