### ISSUE TITLE
No operation imports?

### ISSUE THREAD

**Issue by daeolc** [unchase/Unchase.Odata.Connectedservice#55]
I'm obviously very green to messing with OData in any way shape or form so I'm hoping this is an easy question to answer.

I'm able to get to the last step in adding the connected Microsoft Dynamics NAV service I need however I do not see anything in the "Operation Imports Selection" window.  Can anyone shed some light on what I'm doing wrong or what step I missed?

Thanks

**Comment by unchase** [comment]
Hi, @daeolc 
Probably your schema (metadata file) has no operation imports.
Could you show your metadata?
