### ISSUE TITLE
Unexpected token error when adding connected service

### ISSUE THREAD

**Issue by axellejamous** [unchase/Unchase.Odata.Connectedservice#59]
When trying to add a connected service for a Dynamics 365 endpoint I get an error saying ">" is an unexpected token. 
The expected token is '='. Line 13, position 74.
Is this related to my endpoint or to the extension?

My endpoint is in this format: https://endpointname.dynamics.com/$metadata

Here is the [screenshot](https://imgur.com/a/25fyl65) of the error when I click 'next' or 'finish'.

**Comment by unchase** [comment]
Hi, @axellejamous 
I guess the issue is in the metadata. Can you show your metadata?

**Comment by axellejamous** [comment]
Apparently the third party I am working with gave me the wrong metadata endpoint. 
It was /data instead of /$metadata, yet they kept assuring me /$metadata was correct, so I didn't question it until I showed them your comment saying you should be able to see something.
It works wonderfully now, thank you!

**Comment by unchase** [comment]
You are welcome.
