### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yksokolova** [unchase/Unchase.Odata.Connectedservice#6]
### Describe the bug
Hi Nickolay,

Have an issue with generating template. Using VS 2019 Community Version 16.1.1

Trying to replicate:
https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-client-app
Using your .gif file as a sample
Everything works when i don't add the code template.

But getting errors when try to check "Add code templates...:
In your image after you check it you choose from the drop down ...
But when i check it (place the check mark) i don't see any drop downs to appear...
As the result I'm getting an error and nothing is generated.

Is it possible to generate the template and add it to the project?

Please suggest

Thank you, Elena

### Assemblies affected

*Which assemblies and versions are known to be affected?*

### Steps to reproduce

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue:*

...

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known.*

**Comment by unchase** [comment]
Did you check "Add code templates (Whether to include the T4 files into this project)."? This checkbox is available for OData v4 enpoint. Then you will not see the drop-down menu, since it is intended only for OData v3 (not for OData v4 which endpoint you are using).
