### ISSUE TITLE
Needs updated to work with VS 2022

### ISSUE THREAD

**Issue by ImGonaRot** [unchase/Unchase.Odata.Connectedservice#63]
Please update it so it will work with VS 2022.

**Comment by unchase** [comment]
Hi, @ImGonaRot
I'll try to find time next weekend.

**Comment by unchase** [comment]
Unfortunately, I don't have enough time right now to do this. But I will port the extension to VS2022 a few later.

**Comment by lorenzoviola** [comment]
Hello,

I think that even better would be to launch from command line the odata client class generator

Maybe is it already possible in some way ? 
It would get the settings from json file, execute and generate .CS file

**Comment by mobenn** [comment]
Can i give you a hand on that?

**Comment by lorenzoviola** [comment]
Hello, yes, I'll give a try !
Would you create a branch where I could work ?

**Comment by lorenzoviola** [comment]
Hello, that's an idea !
Maybe unchase could create a branch, where other make a try on the "command line"

**Comment by unchase** [comment]
> Can i give you a hand on that?

Hi, @mobenn
Of course, if you have a desire or experience, then this is only welcome!

**Comment by unchase** [comment]
Hi

I recently added Visual Studio 2022 support for [Unchase.OpenAPI.Connectedservice](https://github.com/unchase/Unchase.OpenAPI.Connectedservice).

The next in line is the Unchase.OData.Connectedservice expansion. I plan to finish this weekend unless urgent matters come up.

**Comment by Odraio** [comment]
@unchase Could you please provide an update about the support of Unchase.OData.Connectedservice in VS 2022?

**Comment by unchase** [comment]
@Odraio @lorenzoviola @mobenn Added in [v1.5.0](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservicevs22)

**Comment by lorenzoviola** [comment]
@unchase Great work !! thank you for your efforts !

**Comment by unchase** [comment]
You are welcome

**Comment by mobenn** [comment]
Awesome work

**Comment by mobenn** [comment]
Can tou make it available for Visual studio 2022 ARM please? Thanks in advance
