### ISSUE TITLE
NOT A BUG: I do not understand, if I can generate with Unchase an OData Client for .NET 6.0 (fka. .NET Core)

### ISSUE THREAD

**Issue by klacol** [unchase/Unchase.Odata.Connectedservice#66]
Hi, I use unchase for many years. In .NET 4.x Projects (Classic .NET Framework). Now I migratae those projects to .NET 6.0 (fka .NET Core).

I really do not get it, if Unchase can also generate a client for .NET 6.0, or not, Is it a tool question (VS 2019, VS 2022) or not?

Any help appreciated.

**Comment by unchase** [comment]
Hi, @klacol 

Prior to Visual Studio 2022, extensions were created using an old SDK, and with the arrival of the new version, the SDK has changed.

Certain code changes need to be made for the extension to also work for VS 2022 and .NET 6

I will try to find time for this, but so far I have a very tight schedule.
