### ISSUE TITLE
DOC

### ISSUE THREAD

**Issue by craigkelly84** [unchase/Unchase.Odata.Connectedservice#70]
Pagination. How to?

**Comment by unchase** [comment]
Hi, @craigkelly84 
See: https://docs.microsoft.com/en-us/odata/client/pagination

**Comment by craigkelly84** [comment]
Hi,

I did try that example already. It does not work with the unchase odata
connected service.
Can you send me another example that works with an unchase odata connected
service?

Regards,
Craig
