### ISSUE TITLE
Error during Update Connected Service in VS2022

### ISSUE THREAD

**Issue by starsoftnl** [unchase/Unchase.Odata.Connectedservice#73]
When updating a unchase odata connected service there is a message box with below text and the service is not updated.

The Connected Services component 'Unchase OData Connected Service' failed: (HRESULT:0x80131509) RunSynchronously may not be called on a task that has allready completed.

Deleting the service and then adding it new works.

**Comment by unchase** [comment]
Hi @starsoftnl
Could you check it now?

**Comment by starsoftnl** [comment]
Hi Chebotov,
The problem is solved. 
Thx
