### ISSUE TITLE
Issue with VS Pro 2022 - 17.2, No context menu option to update/run.

### ISSUE THREAD

**Issue by jimnkey** [unchase/Unchase.Odata.Connectedservice#77]
Context menu doesn't appear with update 17.2

Right clicking on an existing folder under Connected Services no longer gives an option for "Update Unchase OData Connected Services..."

Have tried re-installing.
Have tried rebuilding the extension within 17.2 (and re-installing).
Have NOT tried modifying anything yet.

Posting here to see if this is a known issue... Thanks!

**Comment by ladislavjenicek** [comment]
The problem persists even after updating to a newer version Visual Studio 17.2.1

**Comment by dotnetero** [comment]
I have the same behavior with VS Community. 
Is it possible to return to version 17.1 of Visual Studio 2022? 
Thank you.

**Comment by ericcanadas** [comment]
Same issue here with VS 2022 17.2.1.
But it seem to be a VS 2022 issue than the unchase extension

**Comment by dotnetero** [comment]
Nice day. 
Notice that when you open the add connected services screen in the project you are required to add/update the reference. 
Clicking Unchase OData Connected Service, allows you to open the configuration screen and create the reference again, adding or updating the existing one.

**Comment by ImGonaRot** [comment]
This is still broken even in VS 2022 17.2.6

**Comment by unchase** [comment]
Hi.
This is a problem with Visual Studio. We need to wait for a new release - [Microsoft Dev Community issue](https://developercommunity.visualstudio.com/t/Connected-Services-plugins-cant-update/10070285).

P.S. `Fixed in version 17.3 Preview 4`
