### ISSUE TITLE
Missing [global::Microsoft.OData.Client.ContainerProperty] on DynamicProperties

### ISSUE THREAD

**Issue by MarkusBux** [unchase/Unchase.Odata.Connectedservice#79]
### Describe the bug
Creating an OData Client which uses open types / dynamic properties, does generate the property, but does not put the `[global::Microsoft.OData.Client.ContainerProperty]` attribute on it. Therefore, it is not used as container property.

### Assemblies affected
n/a

### Steps to reproduce
1. Create an OData client of a service that uses open types
2. Query the type
3. Verify that the dynamic properties are not loaded
...

### Expected result
Open type / dynamic properties are loaded into the Dictionary<string, object>

### Actual result
Open type / dynamic properties are not loaded into the Dictionary<string, object>

### Screenshots
'-

### Additional detail
'-

**Comment by VatroslavSrzic** [comment]
Any chance of providing this fix any time soon.

**Comment by unchase** [comment]
Hi, @MarkusBux @VatroslavSrzic 

This functionality probably was implemented in [OdataConnectedService](https://github.com/OData/ODataConnectedService)
I recommend using this solution, as I support it to a greater extent.

You can also propose a PR with changes.
