### ISSUE TITLE
Use from VS Code

### ISSUE THREAD

**Issue by hkusulja** [unchase/Unchase.Odata.Connectedservice#9]
Once configured in Visual Studio 2019 , connected to Microsoft Dynamics 365 CRM Odata metadata endpoint.
I need to be able to call your .exe from command prompt and use Visual Studio Code for further development. Please explain in docs how this can be achieved.

**Comment by unchase** [comment]
Hi, @hkusulja.

You just need to generate the client code using the Connected Service, and then open a project with it in Visual Studio Code. Or copy the generated files to Visual Studio Code.

**Comment by hkusulja** [comment]
@unchase but if I do not have Visual Studio 2019 at all, and using only VS Code?

**Comment by unchase** [comment]
The Connected Service is not exe-file. This is Visual Studio extension integrated into IDE. So, unfortunately, now does not support using it from VS Code.
You need to generate client code once from VS 2017/2019 (Community version will do) and use it in VS Code.
See [how to](https://medium.com/@unchase/how-to-generate-c-or-visual-basic-client-code-for-odata-protocol-versions-1-0-4-0-a3a4f9402ea1).
